import MotionLazyContainer from '@/components/animate/MotionLazyContainer'
import './globals.css'
import { Roboto } from 'next/font/google';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['vietnamese'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} flex min-h-screen flex-col`}>
        <MotionLazyContainer>{children}</MotionLazyContainer>
      </body>
    </html>
  );
}
